steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        "build",
        "-t", "gcr.io/${_PROJECT_ID}/${_JOB_NAME}",
        "-f", "Dockerfile",
        "."
      ]

images:
  - "gcr.io/${_PROJECT_ID}/${_JOB_NAME}"
