name: Deploy to Cloud Run

on:
  push:
    branches: [main]

env:
  PROJECT_ID: daring-thought-467213-m5
  REGION: us-central1
  SERVICE_NAME: embedding-service

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy to Cloud Run
        run: |
          gcloud builds submit --config cloudbuild.yaml --project=$PROJECT_ID
